# charts/backend/values.yaml
image: pkonieczny321/fullstackapp-backend:latest
port: 5000
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
env:
  DATABASE_URL: postgres://postgres:postgres@postgres-postgres:5432/mydb