# charts/backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "backend.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http